### ISSUE TITLE
call with url 

### ISSUE THREAD

**Issue by rastermechanism** [chrismattmann/tika-python#108]
[tika.py: Retrieving http://www.assignmenthelp.net/ to C:\Users\Rakesh\AppData\Local\Temp/.]

Traceback (most recent call last):
  File "C:\Users\Rakesh\Anaconda3\lib\site-packages\tika\tika.py", line 368, in getRemoteFile
    urlretrieve(urlOrPath, destPath)
  File "C:\Users\Rakesh\Anaconda3\lib\urllib\request.py", line 197, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Rakesh\\AppData\\Local\\Temp/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "prg.py", line 7, in <module>
    parsed = parser.from_file(fileUrl, tikServer)
  File "C:\Users\Rakesh\Anaconda3\lib\site-packages\tika\parser.py", line 25, in from_file
    jsonOutput = parse1('all', filename, serverEndpoint)
  File "C:\Users\Rakesh\Anaconda3\lib\site-packages\tika\tika.py", line 184, in parse1
    path, file_type = getRemoteFile(urlOrPath, TikaFilesPath)
  File "C:\Users\Rakesh\Anaconda3\lib\site-packages\tika\tika.py", line 378, in getRemoteFile
    urlretrieve(urlOrPath, destPath)
  File "C:\Users\Rakesh\Anaconda3\lib\urllib\request.py", line 197, in urlretrieve
    tfp = open(filename, 'wb')
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Rakesh\\AppData\\Local\\Temp/'

**Comment by chrismattmann** [comment]
Hi @rastermechanism this looks like an issue in that you don't have permission to write to your temp directory.
