### ISSUE TITLE
pdf processing throwing ("No JSON object could be decoded")

### ISSUE THREAD

**Issue by Haridhan** [chrismattmann/tika-python#139]
Pdf processing using tika is throwing the below exception.,
I am using python 2.7 version

Exception:

Thu May 11 22:46:28 2017 WARNING  Tika server returned status: 404
Traceback (most recent call last):
  File "/appbin/ce_project/ibd_core/hari/Ingestion/script/bd_ingest_file.py", line 83, in <module>
    input_df = bd_common_func.ingest_file(file_name,ingest_config_dict['hive_context'],src_file_name,column_delimiter,column_header)
  File "/ldata/appbin/ce_project/ibd_core/hari/Ingestion/script/bd_common_func.py", line 574, in ingest_file
    parsedPDF = parser.from_file(filename)
  File "/home/hdhanalx/.local/lib/python2.7/site-packages/tika/parser.py", line 28, in from_file
    return _parse(jsonOutput)
  File "/home/hdhanalx/.local/lib/python2.7/site-packages/tika/parser.py", line 47, in _parse
    realJson = json.loads(jsonOutput[1])
  File "/opt/cloudera/parcels/Anaconda-4.0.0/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/cloudera/parcels/Anaconda-4.0.0/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/cloudera/parcels/Anaconda-4.0.0/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")

**Comment by chrismattmann** [comment]
hi @Haridhan can you 1. attach the PDF file in question? and 2. show me the value of <your tmp dir, e.g., /tmp>/tika-server.log ? Is it giving an error in tika server? Have you tried this PDF against Tika Server?

**Comment by chrismattmann** [comment]
ping @Haridhan

**Comment by Haridhan** [comment]
Below error thrown at tika-server.log 
Error: Could not find or load main class org.apache.tika.server.TikaServerCli

Attached the pdf
[spark.pdf](https://github.com/chrismattmann/tika-python/files/1037488/spark.pdf)

**Comment by Haridhan** [comment]
Hi,Chris,

Below error thrown at tika-server.log
Error: Could not find or load main class
org.apache.tika.server.TikaServerCli

Attached the pdf file which i am processing.

Regards,
Hari

**Comment by chrismattmann** [comment]
What platform are you on?

**Comment by Haridhan** [comment]
Linux
cat /etc/redhat-release
CentOS release 6.5 (Final)

**Comment by Haridhan** [comment]
Any update on here

**Comment by chrismattmann** [comment]
Can you try killall java before trying to restart your python interpreter? Maybe a ghost java proc somewhere? At worst can you bounce the machine and try again?

**Comment by chrismattmann** [comment]
@Haridhan ping

**Comment by chrismattmann** [comment]
please open a new issue if you see this again.
