### ISSUE TITLE
Decode/Encode Issue with Python 3.x

### ISSUE THREAD

**Issue by leungi** [chrismattmann/tika-python#144]
Tested on Environment:
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)]

Parser module runs fine, but not the others (e.g. language, unpack). 

_Code_
from tika import translate
 
filePath = <file path>
 
print(translate.from_file(filePath, 'en', 'en'))
 
>> 
 
Traceback (most recent call last):
 
  File "<ipython-input-3-aab0939eb73c>", line 2, in <module>
    print(translate.from_file(filePath, 'en', 'en'))
 
  File "C:\ProgramData\Anaconda3\lib\site-packages\tika\translate.py", line 22, in from_file
    jsonOutput = doTranslate1(srcLang+':'+destLang, filename, serverEndpoint)
 
  File "C:\ProgramData\Anaconda3\lib\site-packages\tika\tika.py", line 285, in doTranslate1
    verbose, tikaServerJar)
 
  File "C:\ProgramData\Anaconda3\lib\site-packages\tika\tika.py", line 348, in callServer
    data = data.read()
 
  File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
 
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1034: character maps to <undefined>

All modules run fine in Py 2.x. 

#sys.version_info(major=2, minor=7, micro=13, releaselevel='final', serial=0)

**Comment by seyhbold** [comment]
Hi, I have the same issue when using `detect` on Windows using python 3.6.2. 
Is there any workaround until this is fixed?

Thank you very much
seyhbold

**Comment by chrismattmann** [comment]
There is a work-around here. Character encoding issues like the original one posted are usually not TIka's fault...please check your environment, or use the work-around.

**Comment by leungi** [comment]
Noted. Thanks.

Sticking with 2.7 for stability.

**Comment by seyhbold** [comment]
It may not be tika's fault but it could be addressed in tika-python.
Now the `from_file` function is useless for Windows Python3 Users if a file is read from the local filesystem.

**Comment by chrismattmann** [comment]
@seyhbold it definitely could be. I'm not a Python3 user so if you have a test case that demonstrates this, and ideally a fix, I would review/potentially commit both of them. In short, if you have time, help, otherwise, this is not high in my priority queue to fix atm and I would need help anyways since I use Python2.7

**Comment by tomalbrecht** [comment]
Any news on this? Is there a workaround yet?

```
Traceback (most recent call last):
  File "/Users/tom/PycharmProjects/spielwiese/Text/transform_pdf.py", line 24, in <module>
    raw = parser.from_file(file_name)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/tika/parser.py", line 36, in from_file
    jsonOutput = parse1('all', filename, serverEndpoint, headers=headers, config_path=config_path)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/tika/tika.py", line 328, in parse1
    headers, verbose, tikaServerJar, config_path=config_path, rawResponse=rawResponse)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/tika/tika.py", line 537, in callServer
    resp = verbFn(serviceUrl, encodedData, headers=headers, verify=False)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/requests/api.py", line 131, in put
    return request('put', url, data=data, **kwargs)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/tom/anaconda3/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/tom/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Users/tom/anaconda3/lib/python3.6/http/client.py", line 1280, in _send_request
    self.putheader(hdr, value)
  File "/Users/tom/anaconda3/lib/python3.6/http/client.py", line 1212, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 75-77: ordinal not in range(256)
```

**Comment by chrismattmann** [comment]
@tomalbrecht I need a test file and test case and I can spend some time on it in the next few weeks. Thanks.

**Comment by tomalbrecht** [comment]
@chrismattmann here you go. Sorry for the delay.

```from tika import parser
from pathlib import Path

if __name__ == "__main__":

    directory_name = '/Users/tom/Documents/PDFs/KI - Wissensgebiete/'

    data = { 'DESC': 'Testdatenset aus PDFs generiert',
                                'data': [],
                                'file_names': [],
                                'target': [],
                                'target_names': []
                              }

    target_list = []

    for file_path in Path(directory_name).glob(u'**/*.pdf'):

        file_name = str(file_path)

        try:
            raw = parser.from_file(file_name)
        except UnicodeEncodeError:
            print('Fixed UnicodeEncode : ' + file_name)
            try:
                #file_name = fix_utf_filename(file_name)
                raw = parser.from_file(file_name)
            except Exception as e:
                # print('Error - unknown: ' + file_name)
                print(file_name)
                print(e)

        try:
            #print(file_name)
            data['data'].append(raw['content'].encode('utf-8', errors='ignore'))
            data['file_names'].append(file_name)
            #data['target'].append(target_list.index(target))
            data['target_names'].append('Text (LDA) und NLP')
        except (KeyError, AttributeError):
            print('Error - corrupt pdf: ' + file_name)```

I saved these PDFs from Safari -> Safe as PDF.

[Deep learning and Soil Science - Part 1 – Towards Data Science.pdf](https://github.com/chrismattmann/tika-python/files/3255609/Deep.learning.and.Soil.Science.-.Part.1.Towards.Data.Science.pdf)
[Extravagant: Neue Video-KI lässt Amateure tanzen wie Profis.pdf](https://github.com/chrismattmann/tika-python/files/3255610/Extravagant.Neue.Video-KI.lasst.Amateure.tanzen.wie.Profis.pdf)

**Comment by kuraga** [comment]
The same issue. Reopen, please!
