### ISSUE TITLE
Issue with SSL certificate 

### ISSUE THREAD

**Issue by mridulnagpal** [chrismattmann/tika-python#156]
Trace :

2017-09-14 16:48:35,768 [MainThread  ] [INFO ]  Retrieving http://search.maven.org/remotecontent?filepath=org/apache/tika/tika-server/1.15/tika-server-1.15.jar to /tmp/tika-server.jar.
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    parsed = parser.from_file('./R1.pdf', xmlContent=True)
  File "build/bdist.linux-x86_64/egg/tika/parser.py", line 38, in from_file
  File "build/bdist.linux-x86_64/egg/tika/tika.py", line 316, in parse1
  File "build/bdist.linux-x86_64/egg/tika/tika.py", line 510, in callServer
  File "build/bdist.linux-x86_64/egg/tika/tika.py", line 559, in checkTikaServer
  File "build/bdist.linux-x86_64/egg/tika/tika.py", line 665, in getRemoteJar
  File "/usr/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 364, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 377, in http_error
    result = method(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 642, in http_error_302
    headers, data)
  File "/usr/lib/python2.7/urllib.py", line 669, in redirect_internal
    return self.open(newurl)
  File "/usr/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 897, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 859, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 830, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)

**Comment by chrismattmann** [comment]
are you behind a proxy? You may need to download the jar by hand and place it in /tmp, can you try that?

**Comment by chrismattmann** [comment]
no comments since Sept, closing
