### ISSUE TITLE
how to fix Connection reset by peer while reading pdf

### ISSUE THREAD

**Issue by piyushgohel** [chrismattmann/tika-python#166]
Hello,

I am extracting data from PDF using this library. But when i pass PDF, it will raise following error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vrs/Piyush/Projects/selenium_demo/local/lib/python2.7/site-packages/tika/parser.py", line 34, in from_file
    jsonOutput = parse1('all', filename, serverEndpoint)
  File "/home/vrs/Piyush/Projects/selenium_demo/local/lib/python2.7/site-packages/tika/tika.py", line 311, in parse1
    verbose, tikaServerJar, rawResponse=rawResponse)
  File "/home/vrs/Piyush/Projects/selenium_demo/local/lib/python2.7/site-packages/tika/tika.py", line 521, in callServer
    resp = verbFn(serviceUrl, encodedData, headers=headers, verify=False)
  File "/home/vrs/Piyush/Projects/selenium_demo/local/lib/python2.7/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/home/vrs/Piyush/Projects/selenium_demo/local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/vrs/Piyush/Projects/selenium_demo/local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/vrs/Piyush/Projects/selenium_demo/local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/vrs/Piyush/Projects/selenium_demo/local/lib/python2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

I am using ubuntu 14.04 LTS

**Comment by chrismattmann** [comment]
looks like an issue with backend of Tika-server. Make sure nothing is already running on 9998 (try `telnet localhost 9998` and make sure if you find a process it's killed). Then try running it again. If you still can't access 9998 it's likely a firewall issue and check your firewall and make sure it allows for localhost binding on * all ports including 9998.
