### ISSUE TITLE
UnicodeEncodeError on utf8 file names

### ISSUE THREAD

**Issue by r00t1ng** [chrismattmann/tika-python#167]
Hi
I am feeding tika with a filename containing a utf-8 character and I am getting the error here.
Can you suggest a work around?

Thank you

/home/b0b/test/mozilŐ.pdf
Traceback (most recent call last):
  File "tika_initial.py", line 23, in <module>
    parsed = parser.from_file(myFile, 'http://127.0.0.1:9999/tika')
  File "/home/b0b/.local/lib/python3.5/site-packages/tika/parser.py", line 34, in from_file
    jsonOutput = parse1('all', filename, serverEndpoint)
  File "/home/b0b/.local/lib/python3.5/site-packages/tika/tika.py", line 311, in parse1
    verbose, tikaServerJar, rawResponse=rawResponse)
  File "/home/b0b/.local/lib/python3.5/site-packages/tika/tika.py", line 521, in callServer
    resp = verbFn(serviceUrl, encodedData, headers=headers, verify=False)
  File "/home/b0b/.local/lib/python3.5/site-packages/requests/api.py", line 126, in put
    return request('put', url, data=data, **kwargs)
  File "/home/b0b/.local/lib/python3.5/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/b0b/.local/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/b0b/.local/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/b0b/.local/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/home/b0b/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/b0b/.local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1146, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.5/http/client.py", line 1078, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u0150' in position 26: ordinal not in range(256)

**Comment by chrismattmann** [comment]
you need to make sure you are using utf-8 encoding to use Tika. Try encoding the filename first and making sure it's utf-8.
