### ISSUE TITLE
 nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by Lubdhak** [chrismattmann/tika-python#173]
```
import tika
from tika import parser
parsed = parser.from_file('Lubdhak_Resume_v6.pdf')
print(parsed["metadata"])
print(parsed["content"])
```

Gives me : 

Traceback (most recent call last):
  File "/Users/lubi/Default Folder/WorkSpaces/PycharmProjects/Headway.ai/tika_check.py", line 5, in <module>
    parsed = parser.from_file('Lubdhak_Resume_v6.pdf')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tika/parser.py", line 36, in from_file
    jsonOutput = parse1('all', filename, serverEndpoint, headers=headers)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tika/tika.py", line 316, in parse1
    headers, verbose, tikaServerJar, rawResponse=rawResponse)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tika/tika.py", line 510, in callServer
    serverEndpoint = checkTikaServer(scheme, serverHost, port, tikaServerJar, classpath)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tika/tika.py", line 555, in checkTikaServer
    alreadyRunning = checkPortIsOpen(serverHost, port)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tika/tika.py", line 681, in checkPortIsOpen
    remoteServerIP  = socket.gethostbyname(remoteServerHost)
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

**Comment by chrismattmann** [comment]
hi @Lubdhak this looks like an issue with resolving localhost. Looking at your log msg, it seems like you are on a mac. Please make sure you have an entry in /etc/hosts for localhost. That ought to fix it.

**Comment by Lubdhak** [comment]
My /etc/hosts content:

127.0.0.1        localhost
255.255.255.255 broadcasthost
::1         localhost
fe80::1%lo0  localhost

**Comment by Lubdhak** [comment]
Never ever use any text editor other than vim to edit system files..
[Character Encoding could mysteriously screw you]

**Comment by chrismattmann** [comment]
ahhh did you fix it? was it a problem there?

**Comment by chrismattmann** [comment]
Assuming this is fixed
