### ISSUE TITLE
Max retries exceeded in tika server

### ISSUE THREAD

**Issue by priyanshujain** [chrismattmann/tika-python#180]
I'm getting this error 
ConnectionError: HTTPConnectionPool(host='apache-tika', port=9998): Max retries exceeded with url: /rmeta/text (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f6999105350>: Failed to establish a new connection: [Errno -5] No address associated with hostname',))

And I checked tika-server is runnning on port 9998 and still getting this error.

**Comment by priyanshujain** [comment]
I fixed this issue but another error came 

Sad Face :( .Something went wrong.                                                                                                          
java.io.FileNotFoundException: https:/filters-api.s3.amazonaws.com/media/resumes/dc3a4907-e759-4636-bd6d-c0820e06735c.pdf (No such file or directory)                                                                                                                                  
        at java.io.FileInputStream.open0(Native Method)                                                                                     
        at java.io.FileInputStream.open(FileInputStream.java:195)                                                                           
        at java.io.FileInputStream.<init>(FileInputStream.java:138)                                                                         
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at code4goal.antony.resumeparser.ResumeParserProgram.parseToHTMLUsingApacheTikka(ResumeParserProgram.java:72) 
        at code4goal.antony.resumeparser.ResumeParserProgram.main(ResumeParserProgram.java:272)                                            
[02/May/2018 05:41:14] "POST /api/resumes/internal/ HTTP/1.0" 200 348

**Comment by chrismattmann** [comment]
@priyanshujain the above error is a Java error not a Python one? Try on the dev@tika.apache.org list
