### ISSUE TITLE
TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by pbienst** [chrismattmann/tika-python#274]
Fresh install on Ubuntu, using 'sudo apt-get install libtika-java' and 'sudo pip3 install tika',

Parsing any pdf file with 'parsed = parser.from_file("a.pdf")' fails with

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tika/parser.py", line 36, in from_file
    output = parse1(service, filename, serverEndpoint, headers=headers, config_path=config_path, requestOptions=requestOptions)
  File "/usr/local/lib/python3.6/dist-packages/tika/tika.py", line 321, in parse1
    headers.update({'Accept': responseMimeType, 'Content-Disposition': make_content_disposition_header(path.encode('utf-8') if type(path) is unicode_string else path)})
  File "/usr/local/lib/python3.6/dist-packages/tika/tika.py", line 126, in make_content_disposition_header
    return build_header(os.path.basename(fn)).decode('ascii')
  File "/usr/local/lib/python3.6/dist-packages/rfc6266.py", line 430, in build_header
    if is_token(filename):
  File "/usr/local/lib/python3.6/dist-packages/rfc6266.py", line 370, in is_token
    return all(is_token_char(ch) for ch in candidate)
  File "/usr/local/lib/python3.6/dist-packages/rfc6266.py", line 370, in <genexpr>
    return all(is_token_char(ch) for ch in candidate)
  File "/usr/local/lib/python3.6/dist-packages/rfc6266.py", line 357, in is_token_char
    asciicode = ord(ch)
TypeError: ord() expected string of length 1, but int found
```

**Comment by chrismattmann** [comment]
Looks like an issue with the filename and unicode @pbienst What charset are you using and can you give examples of the filename? What is your locale?

**Comment by pbienst** [comment]
As I mentioned in my report, the filename is simply "a.pdf"...
Here is the pdf: https://www.dropbox.com/s/rfoisx2bw651l08/a.pdf?dl=0

**Comment by chrismattmann** [comment]
the file isn't there anymore and I can't test.... @pbienst
