### ISSUE TITLE
unpack.from_file sometimes fails with error _csv.Error: line contains NUL

### ISSUE THREAD

**Issue by carantunes** [chrismattmann/tika-python#287]
Some ocasional files lead to error  `_csv.Error: line contains NUL` when parsing with function `unpack.from_file`. With `parser.from_file` is sucessfull.

```
Traceback (most recent call last):
  ...
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tika/unpack.py", line 44, in from_file
    return _parse(tarOutput)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/tika/unpack.py", line 90, in _parse
    for metadataLine in metadataReader:
_csv.Error: line contains NUL

```

I am unsure what's causing this. I can however prepare a quickfix to remove null chars from `metadataFile`.

**Comment by carantunes** [comment]
Using /rmeta/text I can see same problematic NULL bytes appear. I can see Tika returns a couple `DigiPath\u0000`

```
  {
    "Content-Type": "application/pdf",
    "Last-Modified": "2006-03-02T08:53:15Z",
    "Last-Save-Date": "2006-03-02T08:53:15Z",
    "X-Parsed-By": [
      "org.apache.tika.parser.DefaultParser",
      "org.apache.tika.parser.pdf.PDFParser"
    ],
    "X-TIKA:embedded_depth": "0",
    "X-TIKA:parse_time_millis": "96",
    "access_permission:assemble_document": "true",
    "access_permission:can_modify": "true",
    "access_permission:can_print": "true",
    "access_permission:can_print_degraded": "true",
    "access_permission:extract_content": "true",
    "access_permission:extract_for_accessibility": "true",
    "access_permission:fill_in_form": "true",
    "access_permission:modify_annotations": "true",
    "date": "2006-03-02T08:53:15Z",
    "dc:format": "application/pdf; version\u003d1.3",
    "dcterms:modified": "2006-03-02T08:53:15Z",
    "meta:save-date": "2006-03-02T08:53:15Z",
    "modified": "2006-03-02T08:53:15Z",
    "pdf:PDFVersion": "1.3",
    "pdf:charsPerPage": [
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0"
    ],
    "pdf:docinfo:creator_tool": "DigiPath\u0000",
    "pdf:docinfo:modified": "2006-03-02T08:53:15Z",
    "pdf:docinfo:producer": "DigiPath\u0000",
    "pdf:encrypted": "false",
    "pdf:hasXFA": "false",
    "pdf:hasXMP": "false",
    "pdf:unmappedUnicodeCharsPerPage": [
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0",
      "0"
    ],
    "xmp:CreatorTool": "DigiPath\u0000",
    "xmpTPg:NPages": "14"
  }
```
