### ISSUE TITLE
Is tika supported with pyspark?

### ISSUE THREAD

**Issue by deepakjindal90** [chrismattmann/tika-python#318]
Hello ,

Can you please help me to tell whether Tika supported on spark cluster or not?

While using tika on local with pyspark i am getting expected result, but while running my app on cluster it is not giving me expected result? Does tika not supported on multinode cluster?

I am getting below error
Caused by: sun.nio.fs.UnixException: No such file or directory
        at sun.nio.fs.UnixNativeDispatcher.getcwd(Native Method)
        at sun.nio.fs.UnixFileSystem.<init>(UnixFileSystem.java:67)
        at sun.nio.fs.LinuxFileSystem.<init>(LinuxFileSystem.java:39)
        at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:46)
        at sun.nio.fs.LinuxFileSystemProvider.newFileSystem(LinuxFileSystemProvider.java:39)
        at sun.nio.fs.UnixFileSystemProvider.<init>(UnixFileSystemProvider.java:56)
        at sun.nio.fs.LinuxFileSystemProvider.<init>(LinuxFileSystemProvider.java:41)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.nio.fs.DefaultFileSystemProvider.createProvider(DefaultFileSystemProvider.java:48)
        at sun.nio.fs.DefaultFileSystemProvider.create(DefaultFileSystemProvider.java:63)
        at java.io.FilePermission.<clinit>(FilePermission.java:187)

**Comment by chrismattmann** [comment]
you may not have permission to write to /tmp check your permissions
