### ISSUE TITLE
404 error in tika2.6.0

### ISSUE THREAD

**Issue by LaniakeaS** [chrismattmann/tika-python#416]
os: ubuntu 20.04
platform: docker container

exceptions:
```
2024-07-23 14:33:07,876 [AnyIO worker] [WARNI]  Tika server returned status: 404
2024-07-23T06:33:07.896537057Z WARNING [2024-07-23 14:33:07,876] [tika.py:562:callServer] Tika server returned status: 404
2024-07-23T06:33:07.913147602Z ERROR [2024-07-23 14:33:07,896] [loader.py:106:load_file_data] Expecting value: line 1 column 1 (char 0)
2024-07-23T06:33:07.913193127Z Traceback (most recent call last):
2024-07-23T06:33:07.913202356Z   File "/workdir/loader.py", line 86, in load_file_data
2024-07-23T06:33:07.913211777Z     docs = parser.parse(blob)
2024-07-23T06:33:07.913219721Z            ^^^^^^^^^^^^^^^^^^
2024-07-23T06:33:07.913227342Z   File "/usr/local/lib/python3.11/site-packages/langchain_core/document_loaders/base.py", line 125, in parse
2024-07-23T06:33:07.913235846Z     return list(self.lazy_parse(blob))
2024-07-23T06:33:07.913243392Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-23T06:33:07.913250652Z   File "/workdir/deepdoc/parser/doc_parser.py", line 13, in lazy_parse
2024-07-23T06:33:07.913258416Z     sections = self(blob)
2024-07-23T06:33:07.913266716Z                ^^^^^^^^^^
2024-07-23T06:33:07.913273697Z   File "/workdir/deepdoc/parser/doc_parser.py", line 28, in __call__
2024-07-23T06:33:07.913282331Z     parsed_doc = parser.from_buffer(file.as_bytes())
2024-07-23T06:33:07.913289971Z                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-23T06:33:07.913297471Z   File "/usr/local/lib/python3.11/site-packages/tika/parser.py", line 72, in from_buffer
2024-07-23T06:33:07.913305377Z     return _parse((status,response))
2024-07-23T06:33:07.913313156Z            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-23T06:33:07.913323986Z   File "/usr/local/lib/python3.11/site-packages/tika/parser.py", line 96, in _parse
2024-07-23T06:33:07.913337032Z     realJson = json.loads(output[1])
2024-07-23T06:33:07.913344592Z                ^^^^^^^^^^^^^^^^^^^^^
2024-07-23T06:33:07.913351942Z   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
2024-07-23T06:33:07.913359376Z     return _default_decoder.decode(s)
2024-07-23T06:33:07.913366406Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-23T06:33:07.913374206Z   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
2024-07-23T06:33:07.913381731Z     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
2024-07-23T06:33:07.913389207Z                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-23T06:33:07.913396632Z   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
2024-07-23T06:33:07.913405146Z     raise JSONDecodeError("Expecting value", s, err.value) from None
2024-07-23T06:33:07.913437951Z json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by chrismattmann** [comment]
I think it had an issue parsing the file on the Tika server end? This isn't in Tika Python though.
