### ISSUE TITLE
Connection refused with Docker python:2.7 image

### ISSUE THREAD

**Issue by Calpicow** [chrismattmann/tika-python#76]
Installed tika-python into `python:2.7` base image, but getting connection refused.

Are there any other dependencies I need to know about?

Output:

```
>>> from tika import parser
>>> parser.from_buffer('init')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tika/parser.py", line 29, in from_buffer
    {'Accept': 'application/json'}, False)
  File "/usr/local/lib/python2.7/site-packages/tika/tika.py", line 245, in callServer
    resp = verbFn(serviceUrl, data=data, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 122, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
>>> parser.from_buffer('init')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/tika/parser.py", line 29, in from_buffer
    {'Accept': 'application/json'}, False)
  File "/usr/local/lib/python2.7/site-packages/tika/tika.py", line 245, in callServer
    resp = verbFn(serviceUrl, data=data, headers=headers)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 122, in put
    return request('put', url, data=data, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
```

**Comment by Calpicow** [comment]
Working after installing Java. Leaving this open since this requirement should be in the docs and/or error message improved.
