### ISSUE TITLE
Tika parser can't handle non-ASCII filenames

### ISSUE THREAD

**Issue by Pehat** [chrismattmann/tika-python#79]
Just copying my log here:

```
2016-02-04 21:41:27,286 root         INFO     Parsing asset /home/renat/data/pdf/Светозвук_в_природе_и_световая_симфония_Скрябина.pdf...
server endpoint: http://10.250.176.36:9998
2016-02-04 21:41:27,294 requests.packages.urllib3.connectionpool INFO     Starting new HTTP connection (1): 10.250.176.36
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/renat/search/text_extractor/text_extractor.py", line 74, in <module>
    text_extractor.parse_text()
  File "/home/renat/search/text_extractor/text_extractor.py", line 35, in parse_text
    parsed_data = tika_parser.from_file(parse_task.filename, self.tika_address)
  File "/home/renat/searchenv/lib/python3.4/site-packages/tika-1.12-py3.4.egg/tika/parser.py", line 25, in from_file
  File "/home/renat/searchenv/lib/python3.4/site-packages/tika-1.12-py3.4.egg/tika/tika.py", line 168, in parse1
  File "/home/renat/searchenv/lib/python3.4/site-packages/tika-1.12-py3.4.egg/tika/tika.py", line 275, in callServer
  File "/home/renat/searchenv/lib/python3.4/site-packages/requests/api.py", line 120, in put
    return request('put', url, data=data, **kwargs)
  File "/home/renat/searchenv/lib/python3.4/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/renat/searchenv/lib/python3.4/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/renat/searchenv/lib/python3.4/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/renat/searchenv/lib/python3.4/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/home/renat/searchenv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/home/renat/searchenv/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.4/http/client.py", line 1137, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.4/http/client.py", line 1177, in _send_request
    self.putheader(hdr, value)
  File "/usr/local/lib/python3.4/http/client.py", line 1109, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 21-29: ordinal not in range(256)

```
I think the reason is that `urlopen` tries to open an url before performing `quote` for local files. Is there proper way to fix it?

**Comment by chrismattmann** [comment]
Do you have a PR for this @Pehat ? Otherwise I'm going to close for now since I don't have the cycles to work on this.

**Comment by chrismattmann** [comment]
if you have a PR please reference and I'll merge.
